// 60Saniye API - Scrape tweets from @buzzhaber profile
// Vercel serverless function

import fs from 'fs';
import path from 'path';

// Local tweets path (generated by Python scraper)
const LOCAL_TWEETS_PATH = path.join(process.cwd(), 'data/tweets.json');

// Target profile
const TARGET_PROFILE = 'buzzhaber';

export default async function handler(req, res) {
    // CORS headers
    res.setHeader('Access-Control-Allow-Credentials', true);
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version');

    if (req.method === 'OPTIONS') {
        return res.status(200).end();
    }

    if (req.method !== 'GET') {
        return res.status(405).json({ error: 'Method not allowed' });
    }

    try {
        const { limit = 20, tweetUrl } = req.query;

        // Video proxy endpoint - extract direct video URL from tweet
        if (tweetUrl) {
            return await handleVideoProxy(tweetUrl, res);
        }

        // Try to read from local buzzhaber tweets.json first
        let tweets = await loadTweetsFromLocal();

        // Filter for buzzhaber profile only
        tweets = tweets.filter(t => t.profile === TARGET_PROFILE);

        // Sort by time (newest first)
        tweets.sort((a, b) => new Date(b.time) - new Date(a.time));

        // Limit results
        tweets = tweets.slice(0, parseInt(limit));

        // Format tweets for frontend
        const formattedTweets = tweets.map(tweet => ({
            id: tweet.id,
            text: tweet.text,
            author: '60Saniye Haber',
            username: `@${TARGET_PROFILE}`,
            time: formatTime(tweet.time),
            media: tweet.media || [],
            hasVideo: tweet.video || false,
            hasImage: tweet.image || false,
            likes: tweet.engagement?.likes || 0,
            retweets: tweet.engagement?.retweets || 0,
            profile: tweet.profile
        }));

        return res.json({
            tweets: formattedTweets,
            total: formattedTweets.length
        });

    } catch (error) {
        console.error('API Error:', error);
        return res.status(500).json({
            error: error.message,
            tweets: getSampleTweets()
        });
    }
}

// Video proxy handler - extract direct video URL from tweet
async function handleVideoProxy(tweetUrl, res) {
    try {
        // Extract tweet ID from URL
        const tweetIdMatch = tweetUrl.match(/status\/(\d+)/);
        if (!tweetIdMatch) {
            return res.status(400).json({ error: 'Invalid tweet URL' });
        }

        const tweetId = tweetIdMatch[1];

        // Fetch the tweet page to extract video URL
        const tweetPageResponse = await fetch(tweetUrl, {
            headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
                'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
            }
        });

        if (!tweetPageResponse.ok) {
            throw new Error(`Failed to fetch tweet: ${tweetPageResponse.status}`);
        }

        const html = await tweetPageResponse.text();

        // Try to extract video URL from HTML
        let videoUrl = null;

        // Method 1: Look for m3u8 playlist URL
        const m3u8Match = html.match(/https:\/\/video\.twimg\.com\/[^"'\s]+\.m3u8[^"'\s]*/g);
        if (m3u8Match && m3u8Match.length > 0) {
            videoUrl = m3u8Match[0];
        }

        // Method 2: Look for mp4 URL
        if (!videoUrl) {
            const mp4Match = html.match(/https:\/\/video\.twimg\.com\/[^"'\s]+\.mp4[^"'\s]*/g);
            if (mp4Match && mp4Match.length > 0) {
                videoUrl = mp4Match[0];
            }
        }

        // Method 3: Look in tweet data (JSON in script tags)
        if (!videoUrl) {
            const dataMatch = html.match(/"video_url":"([^"]+)"/);
            if (dataMatch) {
                videoUrl = dataMatch[1].replace(/\\\//g, '/');
            }
        }

        if (!videoUrl) {
            return res.status(404).json({
                error: 'Video URL not found',
                tweetId: tweetId,
                fallbackUrl: tweetUrl
            });
        }

        return res.json({
            tweetId: tweetId,
            videoUrl: videoUrl,
            contentType: videoUrl.includes('.m3u8') ? 'application/x-mpegURL' : 'video/mp4'
        });

    } catch (error) {
        console.error('Video proxy error:', error);
        return res.status(500).json({
            error: error.message,
            fallbackUrl: tweetUrl
        });
    }
}

async function loadTweetsFromLocal() {
    try {
        const tweetsData = fs.readFileSync(LOCAL_TWEETS_PATH, 'utf8');
        return JSON.parse(tweetsData);
    } catch (error) {
        console.log('Local tweets not found, using sample data');
        return getSampleTweets();
    }
}

function formatTime(isoTime) {
    const date = new Date(isoTime);
    const now = new Date();
    const diff = Math.floor((now - date) / 1000); // seconds

    if (diff < 60) return 'Az önce';
    if (diff < 3600) return `${Math.floor(diff / 60)} dk önce`;
    if (diff < 86400) return `${Math.floor(diff / 3600)} saat önce`;
    if (diff < 604800) return `${Math.floor(diff / 86400)} gün önce`;
    return date.toLocaleDateString('tr-TR', { day: 'numeric', month: 'short' });
}

// Sample tweets fallback with video examples
function getSampleTweets() {
    return [
        {
            id: '1',
            text: 'Son dakika! Gelişmeler devam ediyor. Detaylar yakında...',
            profile: 'buzzhaber',
            time: new Date().toISOString(),
            media: [
                {
                    type: 'video',
                    url: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4'
                }
            ],
            video: true,
            image: false,
            engagement: { likes: 1234, retweets: 567 }
        },
        {
            id: '2',
            text: '60Saniye ile en son haberleri takip edin! ⚡ #SonDakika #Haber',
            profile: 'buzzhaber',
            time: new Date(Date.now() - 3600000).toISOString(),
            media: [],
            video: false,
            image: false,
            engagement: { likes: 892, retweets: 234 }
        },
        {
            id: '3',
            text: 'Bu akşamki gündem maddeleri çok önemli. Tüm detaylar videomuzda...',
            profile: 'buzzhaber',
            time: new Date(Date.now() - 7200000).toISOString(),
            media: [
                {
                    type: 'video',
                    url: 'https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4'
                }
            ],
            video: true,
            image: false,
            engagement: { likes: 2456, retweets: 890 }
        }
    ];
}
